# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'shopifychallenge' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for shopifychallenge
  pod 'Alamofire', '~> 4.8'
  pod 'AlamofireImage', '~> 3.5'
  pod 'AlamofireObjectMapper', '~> 5.2'
end
